name: Forwardport changes to main
on:
  push:
    branches:
      - v/*
jobs:
  forwardport:
    strategy:
      matrix:
        branch: ['main']
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Set up git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Check PR for forwardport label
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.12
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         labels: '["forwardport to snapshot"]'
        
      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"

      - name: Checkout branch and cherry-pick
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        run: |
          git fetch
          git checkout ${{ matrix.branch }}
          git cherry-pick -x --strategy=recursive -X theirs $GITHUB_SHA
          git push
